import type { Metadata } from "next";
import "@/styles/globals.css";
// import { Provider } from "react-redux";
// import store from "@/redux/store";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    // <Provider store={store}>
    <html lang="en">
      <body className="font-gilroy-medium antialiased text-lg">{children}</body>
    </html>
    // </Provider>
  );
}
